# Generated by Django 5.2.15 on 2026-07-07 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="role",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Creation timestamp."
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="description",
            field=models.TextField(blank=True, help_text="Optional role description."),
        ),
        migrations.AlterField(
            model_name="role",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Whether the role is active."
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="level",
            field=models.PositiveSmallIntegerField(
                default=1, help_text="Role hierarchy level."
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="name",
            field=models.CharField(
                help_text="Unique role name.", max_length=50, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Last modification timestamp."
            ),
        ),
    ]
