# Generated by Django 5.2.15 on 2026-07-07 15:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roles", "0003_permission_rolepermission"),
    ]

    operations = [
        migrations.AddField(
            model_name="permission",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                help_text="Creation timestamp.",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="permission",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Last modification timestamp."
            ),
        ),
        migrations.AddField(
            model_name="rolepermission",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Last modification timestamp."
            ),
        ),
        migrations.AlterField(
            model_name="rolepermission",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Creation timestamp."
            ),
        ),
    ]
