# Generated by Django 5.2.15 on 2026-07-09 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roles", "0004_permission_created_at_permission_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="permission",
            options={
                "ordering": ["name"],
                "verbose_name": "Permission",
                "verbose_name_plural": "Permissions",
            },
        ),
        migrations.AlterModelOptions(
            name="rolepermission",
            options={
                "ordering": ["role", "permission"],
                "verbose_name": "Role Permission",
                "verbose_name_plural": "Role Permissions",
            },
        ),
        migrations.AlterUniqueTogether(
            name="rolepermission",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="permission",
            name="code",
            field=models.CharField(
                help_text="Unique permission code.", max_length=100, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="permission",
            name="description",
            field=models.TextField(
                blank=True, help_text="Optional description of the permission."
            ),
        ),
        migrations.AlterField(
            model_name="permission",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Indicates whether the permission is active."
            ),
        ),
        migrations.AlterField(
            model_name="permission",
            name="name",
            field=models.CharField(
                help_text="Display name of the permission.", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="rolepermission",
            name="permission",
            field=models.ForeignKey(
                help_text="Permission granted to the role.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="roles",
                to="roles.permission",
            ),
        ),
        migrations.AlterField(
            model_name="rolepermission",
            name="role",
            field=models.ForeignKey(
                help_text="Role assigned to the permission.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="permissions",
                to="roles.role",
            ),
        ),
        migrations.AddConstraint(
            model_name="rolepermission",
            constraint=models.UniqueConstraint(
                fields=("role", "permission"), name="unique_role_permission"
            ),
        ),
        migrations.AlterModelTable(
            name="permission",
            table="permissions",
        ),
        migrations.AlterModelTable(
            name="rolepermission",
            table="role_permissions",
        ),
    ]
