# Generated by Django 5.2.15 on 2026-07-10 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Indicates whether the user account is active."
            ),
        ),
    ]
