# Generated by Django 4.2 on 2026-07-11 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_failed_login_attempts_user_locked_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='post_lockout_pending',
            field=models.BooleanField(default=False, help_text='If true, the next failed login after lockout expires will permanently deactivate the account.'),
        ),
    ]
