# Generated by Django 4.2 on 2026-07-11 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_post_lockout_pending'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lockout_cycles',
            field=models.PositiveSmallIntegerField(db_index=True, default=0, help_text='Number of consecutive lockout cycles. Account requires admin unlock when >= LOGIN_MAX_LOCKOUT_CYCLES.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='post_lockout_pending',
            field=models.BooleanField(default=False, help_text='If true, the next login attempt after lockout expires is the final attempt before re-lock.'),
        ),
    ]
