# Generated by Django 4.2 on 2026-07-15 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0001_initial'),
        ('users', '0007_user_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='business',
            field=models.ForeignKey(blank=True, help_text='Business this user belongs to.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='businesses.business'),
        ),
    ]
