# Generated by Django 5.2.15 on 2026-07-15 11:14

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalVerificationToken',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('token_hash', models.CharField(help_text='SHA-256 hash of the raw verification token.', max_length=64)),
                ('purpose', models.CharField(choices=[('email_verification', 'Email Verification'), ('password_reset', 'Password Reset')], help_text='Purpose of this verification token.', max_length=20)),
                ('is_used', models.BooleanField(db_index=True, default=False, help_text='Whether this token has been consumed.')),
                ('expires_at', models.DateTimeField(help_text='Timestamp after which this token is no longer valid.')),
                ('created_at', models.DateTimeField(blank=True, editable=False, help_text='Creation timestamp.')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the client that requested this token.', null=True)),
                ('user_agent', models.CharField(blank=True, help_text='User-Agent header of the client that requested this token.', max_length=512)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, help_text='User this token belongs to.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Verification Token',
                'verbose_name_plural': 'historical Verification Tokens',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='VerificationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(help_text='SHA-256 hash of the raw verification token.', max_length=64)),
                ('purpose', models.CharField(choices=[('email_verification', 'Email Verification'), ('password_reset', 'Password Reset')], help_text='Purpose of this verification token.', max_length=20)),
                ('is_used', models.BooleanField(db_index=True, default=False, help_text='Whether this token has been consumed.')),
                ('expires_at', models.DateTimeField(help_text='Timestamp after which this token is no longer valid.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation timestamp.')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the client that requested this token.', null=True)),
                ('user_agent', models.CharField(blank=True, help_text='User-Agent header of the client that requested this token.', max_length=512)),
                ('user', models.ForeignKey(help_text='User this token belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='verification_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Verification Token',
                'verbose_name_plural': 'Verification Tokens',
                'db_table': 'verification_tokens',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'purpose'], name='idx_vtoken_user_purpose')],
            },
        ),
    ]
