# Generated by Django 5.2.15 on 2026-07-16 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
        ("businesses", "0003_alter_business_kra_pin_and_more"),
        ("roles", "0006_historicalpermission_historicalrole_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserInvitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token_hash",
                    models.CharField(
                        db_index=True,
                        help_text="SHA-256 hash of the raw invitation token.",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        db_index=True,
                        help_text="Email address of the invited user.",
                        max_length=254,
                    ),
                ),
                (
                    "is_used",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether this invitation has been accepted.",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="Timestamp after which this invitation is no longer valid."
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Creation timestamp."
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="IP address of the requester.", null=True
                    ),
                ),
                (
                    "business",
                    models.ForeignKey(
                        help_text="Business the invited user will belong to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitations",
                        to="businesses.business",
                    ),
                ),
                (
                    "invited_by",
                    models.ForeignKey(
                        help_text="User who sent this invitation.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        help_text="Role to assign to the invited user.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitations",
                        to="roles.role",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Invitation",
                "verbose_name_plural": "User Invitations",
                "db_table": "user_invitations",
                "ordering": ["-created_at"],
            },
        ),
    ]
