# Generated by Django 5.2.15 on 2026-07-17 05:46

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0004_alter_business_email_alter_historicalbusiness_email_and_more'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Plan name (e.g. Starter, Standard).', max_length=50, unique=True)),
                ('slug', models.SlugField(help_text='URL-safe identifier.', unique=True)),
                ('description', models.TextField(blank=True, help_text='Plan description.')),
                ('monthly_price', models.DecimalField(decimal_places=2, help_text='Monthly billing price.', max_digits=10)),
                ('annual_price', models.DecimalField(decimal_places=2, help_text='Annual billing price.', max_digits=10)),
                ('max_users', models.PositiveIntegerField(default=5, help_text='Maximum number of users allowed.')),
                ('max_branches', models.PositiveIntegerField(default=1, help_text='Maximum number of branches allowed.')),
                ('max_products', models.PositiveIntegerField(default=500, help_text='Maximum number of products allowed.')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this plan is available for purchase.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation timestamp.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp.')),
            ],
            options={
                'verbose_name': 'Subscription Plan',
                'verbose_name_plural': 'Subscription Plans',
                'db_table': 'subscription_plans',
                'ordering': ['monthly_price'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalSubscriptionPlan',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Plan name (e.g. Starter, Standard).', max_length=50)),
                ('slug', models.SlugField(help_text='URL-safe identifier.')),
                ('description', models.TextField(blank=True, help_text='Plan description.')),
                ('monthly_price', models.DecimalField(decimal_places=2, help_text='Monthly billing price.', max_digits=10)),
                ('annual_price', models.DecimalField(decimal_places=2, help_text='Annual billing price.', max_digits=10)),
                ('max_users', models.PositiveIntegerField(default=5, help_text='Maximum number of users allowed.')),
                ('max_branches', models.PositiveIntegerField(default=1, help_text='Maximum number of branches allowed.')),
                ('max_products', models.PositiveIntegerField(default=500, help_text='Maximum number of products allowed.')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this plan is available for purchase.')),
                ('created_at', models.DateTimeField(blank=True, editable=False, help_text='Creation timestamp.')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, help_text='Last modification timestamp.')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Subscription Plan',
                'verbose_name_plural': 'historical Subscription Plans',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('annual', 'Annual')], help_text='Monthly or annual billing.', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount paid for this subscription period.', max_digits=10)),
                ('start_date', models.DateField(help_text='Subscription start date.')),
                ('end_date', models.DateField(db_index=True, help_text='Subscription end date.')),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled')], db_index=True, default='active', help_text='Current subscription status.', max_length=20)),
                ('auto_renew', models.BooleanField(default=False, help_text='Whether this subscription should auto-renew.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation timestamp.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp.')),
                ('business', models.ForeignKey(help_text='Business this subscription belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='businesses.business')),
                ('payment', models.ForeignKey(blank=True, help_text='Payment that activated this subscription.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='payments.payment')),
                ('plan', models.ForeignKey(help_text='Subscription plan.', on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscriptions.subscriptionplan')),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
                'db_table': 'subscriptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalSubscription',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('annual', 'Annual')], help_text='Monthly or annual billing.', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount paid for this subscription period.', max_digits=10)),
                ('start_date', models.DateField(help_text='Subscription start date.')),
                ('end_date', models.DateField(db_index=True, help_text='Subscription end date.')),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled')], db_index=True, default='active', help_text='Current subscription status.', max_length=20)),
                ('auto_renew', models.BooleanField(default=False, help_text='Whether this subscription should auto-renew.')),
                ('created_at', models.DateTimeField(blank=True, editable=False, help_text='Creation timestamp.')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, help_text='Last modification timestamp.')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('business', models.ForeignKey(blank=True, db_constraint=False, help_text='Business this subscription belongs to.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='businesses.business')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(blank=True, db_constraint=False, help_text='Payment that activated this subscription.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='payments.payment')),
                ('plan', models.ForeignKey(blank=True, db_constraint=False, help_text='Subscription plan.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='subscriptions.subscriptionplan')),
            ],
            options={
                'verbose_name': 'historical Subscription',
                'verbose_name_plural': 'historical Subscriptions',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
