import {
    LayoutDashboard,
    ShoppingCart,
    Users,
    Truck,
    Package,
    Tag,
    Warehouse,
    ShoppingBag,
    Receipt,
    BarChart3,
    Shield,
    KeyRound,
    Bell,
    Settings,
} from "lucide-react"

import type { SidebarMenuItem } from "@/types/navigation/sidebar.types"
import { PermissionCode } from "@/types/enums/permission.enums"

export const SIDEBAR_MENU_CONFIG: SidebarMenuItem[] = [
    {
        id: "dashboard",
        label: "Dashboard",
        icon: LayoutDashboard,
        path: "/",
        group: "main",
        order: 1,
        requiredPermissions: [PermissionCode.DASHBOARD_VIEW],
    },
    {
        id: "pos",
        label: "POS",
        icon: ShoppingCart,
        path: "/pos",
        group: "sales",
        order: 1,
        requiredPermissions: [PermissionCode.SALE_VIEW],
    },
    {
        id: "suppliers",
        label: "Suppliers",
        icon: Truck,
        path: "/suppliers",
        group: "sales",
        order: 3,
        requiredPermissions: [PermissionCode.SUPPLIER_VIEW],
        children: [
            {
                id: "supplier-list",
                label: "Supplier List",
                icon: Truck,
                path: "/suppliers",
                requiredPermissions: [PermissionCode.SUPPLIER_VIEW],
            },
            {
                id: "supplier-create",
                label: "Add Supplier",
                icon: Truck,
                path: "/suppliers/create",
                requiredPermissions: [PermissionCode.SUPPLIER_CREATE],
            },
        ],
    },
    {
        id: "products",
        label: "Products",
        icon: Package,
        path: "/products",
        group: "inventory",
        order: 1,
        children: [
            {
                id: "product-list",
                label: "Product List",
                icon: Package,
                path: "/products",
            },
            {
                id: "product-create",
                label: "Add Product",
                icon: Package,
                path: "/products/create",
            },
        ],
    },
    {
        id: "categories",
        label: "Categories",
        icon: Tag,
        path: "/categories",
        group: "inventory",
        order: 2,
    },
    {
        id: "inventory",
        label: "Inventory",
        icon: Warehouse,
        path: "/inventory",
        group: "inventory",
        order: 3,
        requiredPermissions: [PermissionCode.INVENTORY_VIEW],
    },
    {
        id: "purchases",
        label: "Purchases",
        icon: ShoppingBag,
        path: "/purchases",
        group: "inventory",
        order: 4,
        children: [
            {
                id: "purchase-list",
                label: "Purchase List",
                icon: ShoppingBag,
                path: "/purchases",
            },
            {
                id: "purchase-create",
                label: "Add Purchase",
                icon: ShoppingBag,
                path: "/purchases/create",
            },
        ],
    },
    {
        id: "expenses",
        label: "Expenses",
        icon: Receipt,
        path: "/expenses",
        group: "finance",
        order: 1,
        children: [
            {
                id: "expense-list",
                label: "Expense List",
                icon: Receipt,
                path: "/expenses",
            },
            {
                id: "expense-create",
                label: "Add Expense",
                icon: Receipt,
                path: "/expenses/create",
            },
        ],
    },
    {
        id: "reports",
        label: "Reports",
        icon: BarChart3,
        path: "/reports",
        group: "finance",
        order: 2,
        requiredPermissions: [PermissionCode.REPORT_VIEW],
    },
    {
        id: "users",
        label: "Users",
        icon: Users,
        path: "/users",
        group: "administration",
        order: 1,
        requiredPermissions: [PermissionCode.USER_VIEW],
        children: [
            {
                id: "user-list",
                label: "User List",
                icon: Users,
                path: "/users",
                requiredPermissions: [PermissionCode.USER_VIEW],
            },
            {
                id: "user-create",
                label: "Add User",
                icon: Users,
                path: "/users/create",
                requiredPermissions: [PermissionCode.USER_CREATE],
            },
        ],
    },
    {
        id: "roles",
        label: "Roles",
        icon: Shield,
        path: "/roles",
        group: "administration",
        order: 2,
        requiredPermissions: [PermissionCode.ROLE_VIEW],
        children: [
            {
                id: "role-list",
                label: "Role List",
                icon: Shield,
                path: "/roles",
                requiredPermissions: [PermissionCode.ROLE_VIEW],
            },
            {
                id: "role-create",
                label: "Add Role",
                icon: Shield,
                path: "/roles/create",
                requiredPermissions: [PermissionCode.ROLE_CREATE],
            },
        ],
    },
    {
        id: "permissions",
        label: "Permissions",
        icon: KeyRound,
        path: "/permissions",
        group: "administration",
        order: 3,
        requiredPermissions: [PermissionCode.PERMISSION_VIEW],
        children: [
            {
                id: "permission-list",
                label: "Permission List",
                icon: KeyRound,
                path: "/permissions",
                requiredPermissions: [PermissionCode.PERMISSION_VIEW],
            },
        ],
    },
    {
        id: "notifications",
        label: "Notifications",
        icon: Bell,
        path: "/notifications",
        group: "system",
        order: 1,
    },
    {
        id: "settings",
        label: "Settings",
        icon: Settings,
        path: "/settings",
        group: "system",
        order: 2,
    },
]
