# Generated by Django 5.2.15 on 2026-07-17 05:46

import django.db.models.deletion
import secrets
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalRegistrationInvitation',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, help_text='Email address to send the invitation to.', max_length=254)),
                ('owner_name', models.CharField(help_text='Name of the business owner.', max_length=150)),
                ('business_name', models.CharField(help_text='Name of the business being registered.', max_length=100)),
                ('token_hash', models.CharField(db_index=True, help_text='SHA-256 hash of the raw invitation token.', max_length=64)),
                ('is_used', models.BooleanField(db_index=True, default=False, help_text='Whether this invitation has been used.')),
                ('expires_at', models.DateTimeField(help_text='Timestamp after which this invitation expires.')),
                ('created_at', models.DateTimeField(blank=True, editable=False, help_text='Creation timestamp.')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Registration Invitation',
                'verbose_name_plural': 'historical Registration Invitations',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=secrets.token_urlsafe, help_text='Public unique identifier for this payment.', unique=True)),
                ('owner_name', models.CharField(help_text='Full name of the business owner.', max_length=150)),
                ('owner_email', models.EmailField(help_text='Email address of the business owner.', max_length=254)),
                ('owner_phone', models.CharField(blank=True, help_text='Phone number of the business owner.', max_length=20)),
                ('business_name', models.CharField(help_text='Name of the business being registered.', max_length=100)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('annual', 'Annual')], help_text='Monthly or annual billing.', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount.', max_digits=10)),
                ('currency', models.CharField(default='KES', help_text='ISO 4217 currency code.', max_length=3)),
                ('payment_method', models.CharField(choices=[('mpesa', 'M-Pesa'), ('bank_transfer', 'Bank Transfer'), ('cash', 'Cash'), ('card', 'Card'), ('airtel_money', 'Airtel Money'), ('other', 'Other')], help_text='External payment method used.', max_length=20)),
                ('reference_number', models.CharField(blank=True, help_text='Transaction or reference number from the external payment.', max_length=100)),
                ('payment_date', models.DateField(help_text='Date the payment was made externally.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], db_index=True, default='pending', help_text='Current payment status.', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, help_text='Timestamp when the payment was verified.', null=True)),
                ('notes', models.TextField(blank=True, help_text='Optional notes about the payment.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation timestamp.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp.')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'db_table': 'payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('verified', 'Verified'), ('invitation_sent', 'Invitation Sent'), ('invitation_resent', 'Invitation Resent'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded'), ('updated', 'Updated')], help_text='Action performed on the payment.', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Human-readable description of the action.')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When this action was performed.')),
            ],
            options={
                'verbose_name': 'Payment Audit Log',
                'verbose_name_plural': 'Payment Audit Logs',
                'db_table': 'payment_audit_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='RegistrationInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, help_text='Email address to send the invitation to.', max_length=254)),
                ('owner_name', models.CharField(help_text='Name of the business owner.', max_length=150)),
                ('business_name', models.CharField(help_text='Name of the business being registered.', max_length=100)),
                ('token_hash', models.CharField(db_index=True, help_text='SHA-256 hash of the raw invitation token.', max_length=64, unique=True)),
                ('is_used', models.BooleanField(db_index=True, default=False, help_text='Whether this invitation has been used.')),
                ('expires_at', models.DateTimeField(help_text='Timestamp after which this invitation expires.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation timestamp.')),
            ],
            options={
                'verbose_name': 'Registration Invitation',
                'verbose_name_plural': 'Registration Invitations',
                'db_table': 'registration_invitations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalPayment',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=secrets.token_urlsafe, help_text='Public unique identifier for this payment.')),
                ('owner_name', models.CharField(help_text='Full name of the business owner.', max_length=150)),
                ('owner_email', models.EmailField(help_text='Email address of the business owner.', max_length=254)),
                ('owner_phone', models.CharField(blank=True, help_text='Phone number of the business owner.', max_length=20)),
                ('business_name', models.CharField(help_text='Name of the business being registered.', max_length=100)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('annual', 'Annual')], help_text='Monthly or annual billing.', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount.', max_digits=10)),
                ('currency', models.CharField(default='KES', help_text='ISO 4217 currency code.', max_length=3)),
                ('payment_method', models.CharField(choices=[('mpesa', 'M-Pesa'), ('bank_transfer', 'Bank Transfer'), ('cash', 'Cash'), ('card', 'Card'), ('airtel_money', 'Airtel Money'), ('other', 'Other')], help_text='External payment method used.', max_length=20)),
                ('reference_number', models.CharField(blank=True, help_text='Transaction or reference number from the external payment.', max_length=100)),
                ('payment_date', models.DateField(help_text='Date the payment was made externally.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], db_index=True, default='pending', help_text='Current payment status.', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, help_text='Timestamp when the payment was verified.', null=True)),
                ('notes', models.TextField(blank=True, help_text='Optional notes about the payment.')),
                ('created_at', models.DateTimeField(blank=True, editable=False, help_text='Creation timestamp.')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, help_text='Last modification timestamp.')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Payment',
                'verbose_name_plural': 'historical Payments',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
