# Generated by Django 5.2.15 on 2026-07-17 05:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        ('subscriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpayment',
            name='subscription_plan',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Subscription plan selected.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='subscriptions.subscriptionplan'),
        ),
        migrations.AddField(
            model_name='historicalpayment',
            name='verified_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Super Admin who verified this payment.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalregistrationinvitation',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Super Admin who created this invitation.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalregistrationinvitation',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='subscription_plan',
            field=models.ForeignKey(help_text='Subscription plan selected.', on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='subscriptions.subscriptionplan'),
        ),
        migrations.AddField(
            model_name='payment',
            name='verified_by',
            field=models.ForeignKey(blank=True, help_text='Super Admin who verified this payment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalregistrationinvitation',
            name='payment',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Payment that generated this invitation.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='payments.payment'),
        ),
        migrations.AddField(
            model_name='paymentauditlog',
            name='payment',
            field=models.ForeignKey(help_text='Payment this log entry belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='payments.payment'),
        ),
        migrations.AddField(
            model_name='paymentauditlog',
            name='performed_by',
            field=models.ForeignKey(help_text='User who performed this action.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registrationinvitation',
            name='created_by',
            field=models.ForeignKey(help_text='Super Admin who created this invitation.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_registration_invitations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registrationinvitation',
            name='payment',
            field=models.OneToOneField(help_text='Payment that generated this invitation.', on_delete=django.db.models.deletion.CASCADE, related_name='invitation', to='payments.payment'),
        ),
    ]
