# Generated by Django 4.2 on 2026-07-15 13:11

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalBusiness',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(help_text='Business display name.', max_length=100, validators=[django.core.validators.MinLengthValidator(2)])),
                ('slug', models.SlugField(help_text='URL-safe identifier, auto-generated from name.', max_length=100)),
                ('phone', models.CharField(blank=True, help_text='Business contact phone number.', max_length=20)),
                ('email', models.EmailField(blank=True, help_text='Business contact email address.', max_length=254)),
                ('address', models.TextField(blank=True, help_text='Physical address of the business.')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this business is active.')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft-delete flag.')),
                ('created_at', models.DateTimeField(blank=True, editable=False, help_text='Creation timestamp.')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, help_text='Last modification timestamp.')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, db_constraint=False, help_text='Business owner. Set after the owner user is created.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Business',
                'verbose_name_plural': 'historical Businesses',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Business display name.', max_length=100, validators=[django.core.validators.MinLengthValidator(2)])),
                ('slug', models.SlugField(help_text='URL-safe identifier, auto-generated from name.', max_length=100, unique=True)),
                ('phone', models.CharField(blank=True, help_text='Business contact phone number.', max_length=20)),
                ('email', models.EmailField(blank=True, help_text='Business contact email address.', max_length=254)),
                ('address', models.TextField(blank=True, help_text='Physical address of the business.')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this business is active.')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft-delete flag.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation timestamp.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp.')),
                ('owner', models.ForeignKey(blank=True, help_text='Business owner. Set after the owner user is created.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_businesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Business',
                'verbose_name_plural': 'Businesses',
                'db_table': 'businesses',
                'ordering': ['name'],
            },
        ),
    ]
