# Generated by Django 4.2 on 2026-07-15 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='kra_pin',
            field=models.CharField(blank=True, help_text='KRA PIN for eTIMS tax compliance.', max_length=50),
        ),
        migrations.AddField(
            model_name='historicalbusiness',
            name='kra_pin',
            field=models.CharField(blank=True, help_text='KRA PIN for eTIMS tax compliance.', max_length=50),
        ),
    ]
