# Generated by Django 5.2.15 on 2026-07-16 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("businesses", "0002_business_kra_pin_historicalbusiness_kra_pin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="business",
            name="kra_pin",
            field=models.CharField(help_text="Business KRA Pin", max_length=20),
        ),
        migrations.AlterField(
            model_name="historicalbusiness",
            name="kra_pin",
            field=models.CharField(help_text="Business KRA Pin", max_length=20),
        ),
    ]
