# Generated by Django 5.2.15 on 2026-07-17 05:46

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0003_alter_business_kra_pin_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='email',
            field=models.EmailField(help_text='Business contact email address.', max_length=254),
        ),
        migrations.AlterField(
            model_name='historicalbusiness',
            name='email',
            field=models.EmailField(help_text='Business contact email address.', max_length=254),
        ),
        migrations.CreateModel(
            name='HistoricalBranch',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(help_text='Branch name.', max_length=100)),
                ('is_default', models.BooleanField(default=False, help_text='Whether this is the default branch.')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this branch is active.')),
                ('created_at', models.DateTimeField(blank=True, editable=False, help_text='Creation timestamp.')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, help_text='Last modification timestamp.')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('business', models.ForeignKey(blank=True, db_constraint=False, help_text='Business this branch belongs to.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='businesses.business')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Branch',
                'verbose_name_plural': 'historical Branches',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Branch name.', max_length=100)),
                ('is_default', models.BooleanField(default=False, help_text='Whether this is the default branch.')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this branch is active.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation timestamp.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp.')),
                ('business', models.ForeignKey(help_text='Business this branch belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='businesses.business')),
            ],
            options={
                'verbose_name': 'Branch',
                'verbose_name_plural': 'Branches',
                'db_table': 'branches',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('business', 'name'), name='unique_branch_name_per_business')],
            },
        ),
    ]
